import type { Metadata } from "next";

import Footer from "../../../components/Footer";
import Navbar from "../../../components/Navbar";
import NavlinkBar from "../../../components/NavlinkBar";
import { FormContextProvider } from "@/src/context/FormContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
   <div>
      <Navbar />
      <NavlinkBar />
      <FormContextProvider>
      {children}
      </FormContextProvider>
      <Footer />
      </div>
  );
}
